### ISSUE TITLE
shareAppMessage(obj)函数对于“自定义转发图片配置”的支持

### ISSUE THREAD

**Issue by pumpkye** [peony-ma/wxOpenDataContext#10]
/**
     * 主动拉起转发，进入选择通讯录界面。
     */
    function shareAppMessage(object: { title?: string, imageUrl?: string, query?: string, imageUrlId?: string }): void;

/**
     * 监听用户点击右上角菜单的“转发”按钮时触发的事件
     */
    function onShareAppMessage(callback: (res: {
        title: string,
        imageUrl: string,
        query: string
    }) => void): void;

详情参见：https://developers.weixin.qq.com/minigame/dev/tutorial/open-ability/share/share.html#使用审核通过的转发图片

**Comment by peony-ma** [comment]
谢谢您的关注与反馈，已修复！
