### ISSUE TITLE
wx_mini_game.d.ts中接口可选参数问题

### ISSUE THREAD

**Issue by ETRick** [peony-ma/wxOpenDataContext#3]
在调用函数的时候，不少函数的某些参数是可选的，如showModal，现在调用过去的时候需要把所有参数都填写完整，但其实微信并不要求这样，declare这些函数的时候，可选参数可以加上?以声明可选。

**Comment by peony-ma** [comment]
感谢反馈，已修复您所反馈的问题，现在是最新版，更新了可选参数，默认值，合法值等等，基本上所有的都加上了。
