### ISSUE TITLE
一些可选参数被标识为了必选参数

### ISSUE THREAD

**Issue by pumpkye** [peony-ma/wxOpenDataContext#9]
eg. createUserInfoButton
 /** 创建用户信息按钮*/
    function createUserInfoButton(object: {
        type: string,
        text?: string,
        image?: string,
        style: {
            left: number,
            top: number,
            width: number,
            height: number,
            backgroundColor: string,
            borderColor: string,
            borderWidth: number,
            borderRadius: number,
            textAlign: string,
            fontSize: number,
            lineHeight: number
        },
        withCredentials: boolean,
        lang?: string
    }): UserInfoButton;
这里的几个可选参数没有被标记为可选

**Comment by peony-ma** [comment]
非常感谢，现已修复。
